services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
      - "27018:27018"
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
  gochat:
    build:
      context: .                   # Asegúrate de que Dockerfile esté aquí o ajusta la ruta
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy # Espera a que MongoDB pase el healthcheck
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "mongodb:27017", "--", "/gochat-server"]
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    environment:
      - MONGO_URI=mongodb://mongodb:27017

volumes:
  mongodb_data:
